/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Categories: () => import('#controllers/categories_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Products: () => import('#controllers/products_controller'),
  Reports: () => import('#controllers/reports_controller'),
  Session: () => import('#controllers/session_controller'),
}
